[versions]
pluginYml = "0.9.0"
griefPrevention = "18.0.0"
paperApi = "26.2.build.+"
dynmap = "3.7-SNAPSHOT"

[libraries]
griefPrevention = { group = "com.github.TechFortress", name = "GriefPrevention", version.ref  = "griefPrevention" }
paperApi = { group = "io.papermc.paper", name = "paper-api", version.ref = "paperApi" }
dynmapCore = { group = "us.dynmap", name = "DynmapCoreAPI", version.ref = "dynmap" }
dynmapApi = { group = "us.dynmap", name = "dynmap-api", version.ref = "dynmap" }

[plugins]
pluginYml = { id = "de.eldoria.plugin-yml.paper", version.ref = "pluginYml" }
